name: Get Version

on:
  workflow_call:
    inputs:
      project-path:
        description: "Path of csproj file that contains version tag"
        required: true
        type: string
    outputs:
      version:
        description: "Project version"
        value: ${{ jobs.version.outputs.version }}
      is-new:
        description: "if true, Project version is new version"
        value: ${{ jobs.version.outputs.is-new }}
      is-prerelease:
        description: "if true, Project version is pre-release version"
        value: ${{ jobs.version.outputs.is-prerelease }}

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  NUGET_XMLDOC_MODE: skip
  NUGET_PACKAGES: ${{ inputs.nuget-path }}

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      is-new: ${{ steps.get-version.outputs.is-new }}
      is-prerelease: ${{ steps.get-version.outputs.is-prerelease }}
    steps:
      - uses: actions/checkout@v2
      - name: Get Version Action
        uses: ./actions/get-version
        id: get-version
        with:
          project-path: ${{ inputs.project-path }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
