name: Test get-version

on:
  workflow_dispatch:

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  NUGET_XMLDOC_MODE: skip

jobs:
  version:
    uses: ./.github/workflows/get-version.yml
    with:
      project-path: Tests/SimpleProject/SimpleProject.csproj

  test:
    runs-on: ubuntu-latest
    needs: ["version"]
    steps:
      - name: check Verson
        run: |
          test "${{needs.version.outputs.version}}" = "1.0.0" # version
