name: Test format

on:
  workflow_dispatch:

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  NUGET_XMLDOC_MODE: skip

jobs:
  format:
    uses: ./.github/workflows/format.yml
    with:
      target: Tests/SimpleProject/SimpleProject.csproj
