name: Test format

on:
  workflow_dispatch:

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  NUGET_XMLDOC_MODE: skip

jobs:
  workspace:
    runs-on: ubuntu-latest
    outputs:
      workspace: ${{ steps.workspace.outputs.workspace }}
    steps:
      - id: workspace
        run: echo "::set-output name=workspace::${{ github.workspace }}"

  format-default-nulget:
    uses: ./.github/workflows/format.yml
    with:
      target: Tests/SimpleProject/SimpleProject.csproj

  format-local-nulget:
    uses: ./.github/workflows/format.yml
    needs: ["workspace"]
    with:
      target: Tests/SimpleProject/SimpleProject.csproj
      nuget-path: ${{ needs.workspace.outputs.workspace }}/.nuget/packages
