name: Unit test

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      dotnet-version:
        required: true
        type: string
      test-logger:
        required: false
        default: ""
        type: string
      nuget-path:
        required: false
        default: ""
        type: string

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  NUGET_XMLDOC_MODE: skip
  NUGET_PACKAGES: ${{ inputs.nuget-path }}

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
      - uses: actions/cache@v2
        with:
          path: ${{ (inputs.nuget-path != '' && inputs.nuget-path ) || '~/.nuget/packages' }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Build
        run: dotnet build ${{ inputs.target }}
      - name: Test
        run: dotnet test ${{ inputs.target }} --no-build ${{ (inputs.test-logger != '' &&  format('--logger {0}', inputs.test-logger)) || '' }}
