name: Unit test

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      dotnet-version:
        required: true
        type: string
      test-logger:
        required: false
        default: ""
        type: string
      os:
        description: Running os
        required: false
        default: ubuntu-latest
        type: string
      nuget-path:
        description: path of $NUGET_PACKAGES
        required: false
        default: ""
        type: string

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  NUGET_XMLDOC_MODE: skip
  NUGET_PACKAGES: ${{ inputs.nuget-path }}

jobs:
  unittest:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
      - uses: actions/cache@v3
        with:
          path: ${{ (inputs.nuget-path != '' && inputs.nuget-path ) || '~/.nuget/packages' }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/Directory.Build.props') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Build
        run: dotnet build ${{ inputs.target }}
      - name: Test
        run: dotnet test ${{ inputs.target }} --no-build ${{ (inputs.test-logger != '' &&  format('--logger {0}', inputs.test-logger)) || '' }}
